services:
  mitester-app:
    container_name: mitester-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Data__UseMockSqlData=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
    restart: unless-stopped
